[header]
template   = ${HEADER_TEMPLATE}
title      = POKE RANGER2
serial     = YP2E
maker      = 01
revision   = 0
secure-crc = 0x4A05

[rom]
# Do *NOT* change the following line!
storage-type = PROM
fill-tail    = true
fill-with    = 0xFF

[banner]
version   = 1
icon      = ${ICON_PNG}
title     = Pokémon Ranger
subtitle  = Shadows of Almia
developer = Nintendo

[arm9]
static-binary = main.sbin
definitions   = main_defs.sbin
overlay-table = main_table.sbin

[arm7]
static-binary = ${ARM7_STATIC}
definitions   = ${ARM7_DEFINE}
